[package]
name = "scrap-sys"
version = "0.1.0"
authors = ["Chad Retz <chad.retz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
scrap = { git = "https://github.com/rdnt/rust-scrap", branch = "offsets-ids" }
libc = "~0.2"
