[package]
name = "scrap-sys"
version = "0.1.0"
authors = ["Chad Retz <chad.retz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
scrap = { git = "github.com/owenthewizard/scrap", branch = "master" }
libc = "~0.2"
